- name: install Apache
  become: true
  apt:
    name: apache2
    update_cache: yes

- name: enabled mod_rewrite
  apache2_module:
    name: rewrite
    state: present
  
- name: Ensure apache2 is running
  service:
    name: apache2
    state: started
  notify: 
    - restart apache2