- name: Create the database for wordpress
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present

- mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
